version: '3'
services:
  store:
    hostname: store
    container_name: store
    build:
      context: ./store
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
      - auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_AI_GIGACHAT_CLIENT_ID=${SPRING_AI_GIGACHAT_CLIENT_ID}
      - SPRING_AI_GIGACHAT_CLIENT_SECRET=${SPRING_AI_GIGACHAT_CLIENT_SECRET}
      - API_KEY_PROVIDER_URL=http://auth:8080/api/v1/api-key/validate
      - API_KEY_PROVIDER_PASSWORD=store

  chat:
    hostname: chat
    container_name: chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    links:
      - "minio:storage.minio"
    networks:
      - backend
    depends_on:
      - postgres-chat
      - auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-chat:5432/chat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_AWS_S3_URL=http://minio:9000
      - SPRING_AI_GIGACHAT_CLIENT_ID=${SPRING_AI_GIGACHAT_CLIENT_ID}
      - SPRING_AI_GIGACHAT_CLIENT_SECRET=${SPRING_AI_GIGACHAT_CLIENT_SECRET}
      - API_KEY_PROVIDER_URL=http://auth:8080/api/v1/api-key/validate
      - API_KEY_PROVIDER_PASSWORD=store
      - STORE_URL=http://store:8080/api/v1
      - STORE_API_KEY=${SERVICE_API_KEY}

  auth:
    hostname: auth
    container_name: auth
    build:
      context: ./auth/api-key-provider
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - backend
    depends_on:
      - postgres-auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - AUTH_ADMIN_PASSWORD=admin
      - AUTH_STORE_PASSWORD=store

  postgres:
    hostname: postgres
    container_name: postgres
    image: "pgvector/pgvector:pg17"
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres-auth:
    hostname: postgres-auth
    container_name: postgres-auth
    image: "postgres:13"
    ports:
      - "5433:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth

  postgres-chat:
    hostname: postgres-chat
    container_name: postgres-chat
    image: "postgres:13"
    ports:
      - "5434:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat

  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    entrypoint:
      - sh
    command:
      - -c
      - >-
        mkdir -p /data/storage &&
        minio server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
      MINIO_DOMAIN: minio

networks:
  backend:
    driver: bridge