spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql